language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - graphviz
before_install:
  - pip install -U pip setuptools wheel
install:
  - travis_wait travis_retry pip install -r requirements.txt
script: "nosetests bayesian_bootstrap/tests"
